services:
  webhook:
    container_name: webhook
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - npm_networks

networks:
  npm_networks:
    external: true
